name: Compile LaTeX Document and Create Release

on:
  push:
    branches:
      - main  # Ou a branch onde você quer criar releases
  workflow_dispatch:  # Permite iniciar o workflow manualmente, se necessário
  
permissions:
  contents: write
  id-token: write  # Grant the bot permission to push tags
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up TeX environment
        run: |
          sudo apt-get update
          sudo apt-get install -y texlive-full biber

      - name: Initial Compile LaTeX document
        run: |
          pdflatex -interaction=nonstopmode Trabalho.tex
          
          pdflatex -interaction=nonstopmode Trabalho.tex
          pdflatex -interaction=nonstopmode Trabalho.tex

        shell: bash

      - name: Bibliography Compilation
        run: |
          biber Trabalho
            
        shell: bash

      - name: Second Compile LaTeX document
        run: |
          pdflatex -interaction=nonstopmode Trabalho.tex

        shell: bash
      
      - name: Last Compile LaTeX document
        run: |
          pdflatex -interaction=nonstopmode Trabalho.tex
        shell: bash

      - name: Create Tag for Release
        run: |
          VERSION=$(date +'%Y%m%d%H%M%S')  # Example version based on timestamp
          git tag $VERSION
          git push origin $VERSION

      - name: Upload PDF as Release Asset
        if: success()  # Só cria a release se a compilação foi bem-sucedida
        uses: softprops/action-gh-release@v1
        with:
          files: Trabalho.pdf
          tag_name: $VERSION
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
