name: Compile LaTeX Document and Create Release

on:
  push:
    branches:
      - main  # Ou a branch onde você quer criar releases
  workflow_dispatch:  # Permite iniciar o workflow manualmente, se necessário

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up TeX environment
        run: |
          sudo apt-get update
          sudo apt-get install -y texlive-full biber

      - name: Compile LaTeX document
        run: |
          pdflatex Trabalho.tex
          biber Trabalho
          pdflatex Trabalho.tex
          pdflatex Trabalho.tex

        shell: bash

      - name: Upload PDF as Release Asset
        if: success()  # Só cria a release se a compilação foi bem-sucedida
        uses: softprops/action-gh-release@v1
        with:
          files: Trabalho.pdf
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
